# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo:latest
    restart: always
    container_name: afc-richmond-container
    ports:
      - 27017:27017
    command: ["--noauth"]

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081

